<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
    <link>https://forums.pythonic.guru/t/topic/9050</link>
    <description>היי חברים,
ניסיתי להשתמש בsql.orm.Query כשבניתי שאילתת SQL ובשל סיבוכים בסוף העדפתי שלא ומחקתי את הייבוא. לאחר שמחקתי וכבר בניתי קוד בשימוש בפונקציה אחרת עולה לי השגיאה הבאה כאשר הקוד מורץ בטסטים-
![image|690x107](upload://x4dKR6jakNPhtgZuyhRIvBrxZ7J.png) 
כל הסיפור הזה מאוד מוזר כי כבר מחקתי את החלק שהשתמש בclass המדובר.

למשהו יש רעיון מדוע זה יכול לקרות?

מבדיקה שעשיתי נראה כי התקלה היא בשתי השורות המסומנות:
![image|689x164](upload://sRSXDoke1AgW8jnnih7jWHTw8DC.png) 
לא מצליחה להבין מה שגוי בהן, לקחתי את הפורמט מתוך הדוקומנטציה של sqlalchemy</description>
    <language>he</language>
    <lastBuildDate>Sun, 07 Feb 2021 22:06:25 +0000</lastBuildDate>
    <category>שבוע 16</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/9050.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[efratush]]></dc:creator>
        <description><![CDATA[
            <p>לא התעמקתי במה את מנסה לעשות. כרגע הוא מוצא לך את כל האירועים לפי התנאים שהצבת.<br>
אם את רוצה את היחיד או הראשון, תחליפי את all בfirst או one.</p>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/6">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/6</link>
        <pubDate>Sun, 07 Feb 2021 22:06:25 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-6</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[noam100]]></dc:creator>
        <description><![CDATA[
            <p>אכן פתר!!! תודההה <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/5">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/5</link>
        <pubDate>Sun, 07 Feb 2021 20:31:05 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-5</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[efratush]]></dc:creator>
        <description><![CDATA[
            <p>בסוף תסיימי עם</p>
<blockquote>
<p>.all()</p>
</blockquote>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/4</link>
        <pubDate>Sun, 07 Feb 2021 19:58:36 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-4</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[noam100]]></dc:creator>
        <description><![CDATA[
            <p>עדיין אותה שגיאה מופיעה לי <img src="https://forums.pythonic.guru/images/emoji/twitter/confused.png?v=9" title=":confused:" class="emoji" alt=":confused:"><br>
אני חושבת שהתקלה שלי היא שאני לא ממש מבינה את מהות השגיאה… ניסיתי לקרוא ולא הצלחתי להבין</p>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/3</link>
        <pubDate>Sun, 07 Feb 2021 19:54:50 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-3</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[efratush]]></dc:creator>
        <description><![CDATA[
            <p>תנסי:<br>
<code>join(Event, Event.id == UserEvent.event_id)</code></p>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/2</link>
        <pubDate>Sat, 06 Feb 2021 22:43:02 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
      <item>
        <title>עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</title>
        <dc:creator><![CDATA[noam100]]></dc:creator>
        <description><![CDATA[
            <p>היי חברים,<br>
ניסיתי להשתמש בsql.orm.Query כשבניתי שאילתת SQL ובשל סיבוכים בסוף העדפתי שלא ומחקתי את הייבוא. לאחר שמחקתי וכבר בניתי קוד בשימוש בפונקציה אחרת עולה לי השגיאה הבאה כאשר הקוד מורץ בטסטים-<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/e/e7c1ea220c7d24d6f1afe8690f49d57c04ddfd9b.png" data-download-href="https://forums.pythonic.guru/uploads/default/e7c1ea220c7d24d6f1afe8690f49d57c04ddfd9b" title="image"><img src="https://forums.pythonic.guru/uploads/default/original/2X/e/e7c1ea220c7d24d6f1afe8690f49d57c04ddfd9b.png" alt="image" data-base62-sha1="x4dKR6jakNPhtgZuyhRIvBrxZ7J" width="690" height="107" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/e/e7c1ea220c7d24d6f1afe8690f49d57c04ddfd9b_2_10x10.png"></a></div><br>
כל הסיפור הזה מאוד מוזר כי כבר מחקתי את החלק שהשתמש בclass המדובר.<p></p>
<p>למשהו יש רעיון מדוע זה יכול לקרות?</p>
<p>מבדיקה שעשיתי נראה כי התקלה היא בשתי השורות המסומנות:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/c/ca5440f5dabd37a47038d71adfcf1b5ce27d3cc8.png" data-download-href="https://forums.pythonic.guru/uploads/default/ca5440f5dabd37a47038d71adfcf1b5ce27d3cc8" title="image"><img src="https://forums.pythonic.guru/uploads/default/original/2X/c/ca5440f5dabd37a47038d71adfcf1b5ce27d3cc8.png" alt="image" data-base62-sha1="sRSXDoke1AgW8jnnih7jWHTw8DC" width="689" height="164" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/c/ca5440f5dabd37a47038d71adfcf1b5ce27d3cc8_2_10x10.png"></a></div><br>
לא מצליחה להבין מה שגוי בהן, לקחתי את הפורמט מתוך הדוקומנטציה של sqlalchemy<p></p>
          <p><a href="https://forums.pythonic.guru/t/topic/9050/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/9050/1</link>
        <pubDate>Sat, 06 Feb 2021 13:32:52 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9050-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/9050.rss">עזרה- תקלה בטסטים שזוכרים קובץ שאינו קיים</source>
      </item>
  </channel>
</rss>
