<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>יבוא הclassים מתקיית Database</title>
    <link>https://forums.pythonic.guru/t/class-database/8791</link>
    <description>הי,
יש לי בעייה מוזרה אנימריץ את הFASTAPI בתוך CMD נפרד (דרך הסביבה הוירטואלית) ועובד על הVSC בצורה רגילה 
והCMD לא מצליח למצא את התקיות שלי
זאת השגיאה שהוא זורק לי - 
  File &quot;.\create_event.py&quot;, line 12, in &lt;module&gt;
    from app.database.models import Event
ModuleNotFoundError: No module named &#39;app&#39;
ייצוין שהVSC כן מזהה את כל התקיות והאימפורטים כמו שצריך..

עזרה מישהו?</description>
    <language>he</language>
    <lastBuildDate>Sat, 16 Jan 2021 16:19:00 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/class-database/8791.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>יבוא הclassים מתקיית Database</title>
        <dc:creator><![CDATA[mbdi007]]></dc:creator>
        <description><![CDATA[
            <p>אז אפרת המלכה עזרה לי בפרטי, אכן הביעה הייתה שלא הרצתי מהקובץ main</p>
          <p><a href="https://forums.pythonic.guru/t/class-database/8791/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/class-database/8791/4</link>
        <pubDate>Sat, 16 Jan 2021 16:19:00 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8791-4</guid>
        <source url="https://forums.pythonic.guru/t/class-database/8791.rss">יבוא הclassים מתקיית Database</source>
      </item>
      <item>
        <title>יבוא הclassים מתקיית Database</title>
        <dc:creator><![CDATA[Ellen]]></dc:creator>
        <description><![CDATA[
            <p>האם אתה מריץ את האפליקציה מתוך התיקיה app?</p>
          <p><a href="https://forums.pythonic.guru/t/class-database/8791/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/class-database/8791/3</link>
        <pubDate>Fri, 15 Jan 2021 14:44:00 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8791-3</guid>
        <source url="https://forums.pythonic.guru/t/class-database/8791.rss">יבוא הclassים מתקיית Database</source>
      </item>
      <item>
        <title>יבוא הclassים מתקיית Database</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>תוכל לתאר שלב אחר שלב מה אתה עושה ואיפה אתה נמצא מבחינת ה־cmd?</p>
          <p><a href="https://forums.pythonic.guru/t/class-database/8791/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/class-database/8791/2</link>
        <pubDate>Fri, 15 Jan 2021 14:28:00 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8791-2</guid>
        <source url="https://forums.pythonic.guru/t/class-database/8791.rss">יבוא הclassים מתקיית Database</source>
      </item>
      <item>
        <title>יבוא הclassים מתקיית Database</title>
        <dc:creator><![CDATA[mbdi007]]></dc:creator>
        <description><![CDATA[
            <p>הי,<br>
יש לי בעייה מוזרה אנימריץ את הFASTAPI בתוך CMD נפרד (דרך הסביבה הוירטואלית) ועובד על הVSC בצורה רגילה<br>
והCMD לא מצליח למצא את התקיות שלי<br>
זאת השגיאה שהוא זורק לי -<br>
File “.\create_event.py”, line 12, in <br>
from app.database.models import Event<br>
ModuleNotFoundError: No module named ‘app’<br>
ייצוין שהVSC כן מזהה את כל התקיות והאימפורטים כמו שצריך…</p>
<p>עזרה מישהו?</p>
          <p><a href="https://forums.pythonic.guru/t/class-database/8791/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/class-database/8791/1</link>
        <pubDate>Fri, 15 Jan 2021 10:06:59 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8791-1</guid>
        <source url="https://forums.pythonic.guru/t/class-database/8791.rss">יבוא הclassים מתקיית Database</source>
      </item>
  </channel>
</rss>
