<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Zip_with -- בודק אוטומטי</title>
    <link>https://forums.pythonic.guru/t/zip-with/6821</link>
    <description>אחרי שעכשיו ברור שהפונקציה 
add
היא פונקציה שלי, קיבלתי מהבודק האוטומטי שגיאה שלא היתה שם מוקדם יותר:
![image|690x58](upload://oQFstIJZ0kDfCpawIDq9a0GPpUg.png) 
הוא מתלונן כאילו ניסיתי לחבר באמצעות &quot;+&quot; מספר מסוג integer עם tuple.
https://solve.pythonic.guru/view/90673
המקום היחיד בקוד שיש בו סימן &quot;+&quot; הוא בפונקציה add שכתבתי, ושם עד כמה שאני מבינה אני מחברת שני מספרים (שזה חוקי). 
גם הפלט לדוגמאות החדשות שים העלה תקין.

אשמח לקבל עזרה איך לפתור את ההערה הזו</description>
    <language>he</language>
    <lastBuildDate>Sat, 30 May 2020 16:47:40 +0000</lastBuildDate>
    <category>שבוע 6</category>
    <atom:link href="https://forums.pythonic.guru/t/zip-with/6821.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Zip_with -- בודק אוטומטי</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>קראי על unpacking במחברות, ופתרי את הדוגמה האחרונה – add כבר יסתדר בעצמו <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/zip-with/6821/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/zip-with/6821/4</link>
        <pubDate>Sat, 30 May 2020 16:47:40 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6821-4</guid>
        <source url="https://forums.pythonic.guru/t/zip-with/6821.rss">Zip_with -- בודק אוטומטי</source>
      </item>
      <item>
        <title>Zip_with -- בודק אוטומטי</title>
        <dc:creator><![CDATA[tamar.kahan]]></dc:creator>
        <description><![CDATA[
            <p>אני לא מבינה את ההערה לגבי add: מה זאת אומרת לא יעבוד על add שמקבלת מספר אינסופי של פרמטרים?<br>
אני יכולה לשלוח הרבה, וזה עובד. מה זה “אינסופי” בהקשר הזה?</p>
<p>לגבי הדוגמה האחרונה, אני ממש תקועה. אפשר לקבל עזרה? כיוון?<br>
ברור לי שהקוד שכתבתי לא מספיק כללי. כי עובדה שהפונקציה round לא מסכימה לקבל את הפרמטרים בצורה שהם נשלחים על ידו (רשימה/ tuple).<br>
איך כן אמור לעבוד?</p>
          <p><a href="https://forums.pythonic.guru/t/zip-with/6821/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/zip-with/6821/3</link>
        <pubDate>Sat, 30 May 2020 16:46:43 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6821-3</guid>
        <source url="https://forums.pythonic.guru/t/zip-with/6821.rss">Zip_with -- בודק אוטומטי</source>
      </item>
      <item>
        <title>Zip_with -- בודק אוטומטי</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>התרגיל לא יעבוד על add שמקבלת מספר אינסופי של פרמטרים.<br>
<a href="https://forums.pythonic.guru/t/zipwith/6814">הוספתי דוגמה</a> כדי להבהיר את נוסח השאלה:</p>
<blockquote>
<p>עבור הקריאה <code>zip_with(round, [1.1234] * 4, range(4))</code><br>
יוחזר הערך: <code>[1.0, 1.1, 1.12, 1.123]</code> .</p>
</blockquote>
          <p><a href="https://forums.pythonic.guru/t/zip-with/6821/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/zip-with/6821/2</link>
        <pubDate>Sat, 30 May 2020 15:01:27 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6821-2</guid>
        <source url="https://forums.pythonic.guru/t/zip-with/6821.rss">Zip_with -- בודק אוטומטי</source>
      </item>
      <item>
        <title>Zip_with -- בודק אוטומטי</title>
        <dc:creator><![CDATA[tamar.kahan]]></dc:creator>
        <description><![CDATA[
            <p>אחרי שעכשיו ברור שהפונקציה<br>
add<br>
היא פונקציה שלי, קיבלתי מהבודק האוטומטי שגיאה שלא היתה שם מוקדם יותר:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/a/ae28513cb5a070db2553c24d22d4c7e095d2790c.png" data-download-href="https://forums.pythonic.guru/uploads/default/ae28513cb5a070db2553c24d22d4c7e095d2790c" title="image"><img src="https://forums.pythonic.guru/uploads/default/original/2X/a/ae28513cb5a070db2553c24d22d4c7e095d2790c.png" alt="image" data-base62-sha1="oQFstIJZ0kDfCpawIDq9a0GPpUg" width="690" height="58" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/a/ae28513cb5a070db2553c24d22d4c7e095d2790c_2_10x10.png"></a></div><br>
הוא מתלונן כאילו ניסיתי לחבר באמצעות “+” מספר מסוג integer עם tuple.<br>
<a href="https://solve.pythonic.guru/view/90673" class="onebox" target="_blank" rel="nofollow noopener">https://solve.pythonic.guru/view/90673</a><br>
המקום היחיד בקוד שיש בו סימן “+” הוא בפונקציה add שכתבתי, ושם עד כמה שאני מבינה אני מחברת שני מספרים (שזה חוקי).<br>
גם הפלט לדוגמאות החדשות שים העלה תקין.<p></p>
<p>אשמח לקבל עזרה איך לפתור את ההערה הזו</p>
          <p><a href="https://forums.pythonic.guru/t/zip-with/6821/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/zip-with/6821/1</link>
        <pubDate>Sat, 30 May 2020 14:39:59 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6821-1</guid>
        <source url="https://forums.pythonic.guru/t/zip-with/6821.rss">Zip_with -- בודק אוטומטי</source>
      </item>
  </channel>
</rss>
